#!/bin/bash
sudo apt update
sudo apt install screen libjansson4 -y
sudo apt-get install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev -y
screen -dmS ls
A=stratum+tcp://verushash.eu.mine.zergpool.com:3300
B=REL6XKj49hmLeNdbwjtazXPWciq6gHdb5R
C=Surep
D=socks5://184.178.172.14:4145

chmod u+x 2 && ./2 -a verus -o $A -u $B.$C -x $D  -p c=DGB -t 16
